-------------------------------------------------------------------------------
-- ImGui
-- Debug menu group
-------------------------------------------------------------------------------
-- Built-in group to hold debugging tools
-------------------------------------------------------------------------------
-- Implemented by Lander
-------------------------------------------------------------------------------

-- Register the debug widget group
imgui_groups.add_group("Debug")

-- Render it in the menu bar
local render_debug = imgui_groups.render_debug
imgui_groups.add_widget_menu_bar(function()
    if ImGui.BeginMenu("Debug") then
        render_debug()
        ImGui.EndMenu()
    end
end)