-------------------------------------------------------------------------------
-- ImGui
-- Unique widget group
-------------------------------------------------------------------------------
-- Built-in group for rendering independendly of the ImGui overlay
-------------------------------------------------------------------------------
-- Implemented by Lander
-------------------------------------------------------------------------------

-- Register the unique widget group
imgui_groups.add_group("Unique")

-- Render the unique group unconditionally every frame
AddUniqueCall(imgui_groups.render_unique)