local old_trade_manager_trade_init = trade_manager.trade_init
function trade_manager.trade_init(npc, cfg)
    local id = npc:id()
    local reup_time = trade_manager.get_trade_profile(id, "resupply_time")
    old_trade_manager_trade_init(npc, cfg)
    local trade_profile = trade_manager.get_trade_profile(id)
    if not trade_profile then return end
    if not reup_time then return end
    trade_profile.resupply_time = reup_time
end